import {
  LuArrowLeft,
  LuArrowLeftRight,
  LuArrowRight,
  LuArrowUpDown,
  LuAtSign,
  LuBinary,
  LuCalendar,
  LuCheck,
  LuCheckCheck,
  LuChevronLeft,
  LuChevronRight,
  LuChevronUp,
  LuChevronDown,
  //LuCircleFadingPlus,
  LuCircleHelp,
  LuCircleOff,
  LuCloudUpload,
  LuCode,
  LuCopy,
  LuCopyPlus,
  LuCornerDownLeft,
  LuDatabase,
  LuEllipsis,
  LuEllipsisVertical,
  LuFence,
  LuFileLock2,
  LuFileSearch,
  LuFilter,
  LuGlobe,
  LuGrip,
  LuHistory,
  LuIndentIncrease,
  LuKeyRound,
  LuLayers,
  LuLayoutList,
  LuListChecks,
  LuMessageCircleMore,
  LuMessageCircleReply,
  LuMessageCircleCode,
  LuMessagesSquare,
  LuMinus,
  LuNavigation,
  LuPackage,
  LuPackageOpen,
  LuPencil,
  LuPlus,
  LuRefreshCw,
  LuScale,
  LuSearch,
  LuShieldCheck,
  LuSlidersHorizontal,
  LuSquarePlus,
  LuTornado,
  LuTrash2,
  LuTriangleAlert,
  LuUserCheck,
  LuUserRound,
  LuUsersRound,
  LuVariable,
  LuX,
} from "react-icons/lu";

const DEFAULT_ICON_SIZE = 24;

export {
  DEFAULT_ICON_SIZE as ICON_SIZE,
  LuKeyRound as APIKeysIcon,
  LuUserCheck as AccessIcon,
  LuEllipsis as ActionsIcon,
  LuPlus as AddIcon,
  LuLayers as AppIcon,
  LuArrowLeft as BackIcon,
  LuBinary as BinaryIcon,
  LuCalendar as CalendarIcon,
  LuMessageCircleMore as ChatIcon,
  LuMessageCircleCode as ChatWidgetsIcon,
  LuCheck as CheckIcon,
  LuChevronLeft as ChevronLeftIcon,
  LuChevronRight as ChevronRightIcon,
  LuChevronUp as ChevronUpIcon,
  LuChevronDown as ChevronDownIcon,
  LuCopyPlus as CloneIcon,
  LuCode as CodeIcon,
  LuCopy as CopyIcon,
  LuDatabase as DataIcon,
  LuTrash2 as DeleteIcon,
  LuPencil as EditIcon,
  LuAtSign as EmailAgentsIcon,
  LuPackageOpen as EndpointsIcon,
  LuLayoutList as EnvIcon,
  LuMessageCircleReply as FeedbackIcon,
  LuFilter as FilterIcon,
  LuFence as GuardrailsIcon,
  LuUsersRound as GroupIcon,
  LuCircleHelp as HelpIcon,
  LuHistory as HistoryIcon,
  LuGlobe as HTTPIcon,
  LuIndentIncrease as IndentIcon,
  LuFileSearch as IndexesIcon,
  LuArrowLeftRight as IntegrationsIcon,
  LuScale as JudgementIcon,
  LuTornado as MetadataIcon,
  LuEllipsisVertical as MoreIcon,
  LuPackage as ModelsIcon,
  LuMinus as MinusIcon,
  LuArrowRight as NextIcon,
  LuSquarePlus as NewIcon,
  LuPlus as PlusIcon,
  LuFileLock2 as PoliciesIcon,
  LuSlidersHorizontal as ProfilesIcon,
  LuRefreshCw as RefreshIcon,
  LuCornerDownLeft as ReturnIcon,
  LuListChecks as RulesIcon,
  LuShieldCheck as SafetyIcon,
  LuCloudUpload as SaveIcon,
  LuSearch as SearchIcon,
  LuNavigation as SelectIcon,
  LuGrip as ServicesIcon,
  LuMessagesSquare as SessionsIcon,
  LuArrowUpDown as SortIcon,
  LuCircleOff as StopIcon,
  LuCopyPlus as TemplateIcon,
  LuCheckCheck as TestIcon,
  LuVariable as VariableIcon,
  LuUserRound as UserIcon,
  LuTriangleAlert as WarningIcon,
  LuX as XIcon,
  //LuCircleFadingPlus as ContextIcon,
  LuPlus as ContextIcon,
};
